import SudokuLean.Basic
import SudokuLean.Thermometer
import SudokuLean.Symbols4

set_option linter.style.whitespace false

-- puzzle generated by Google Gemini, lets see if it is solvable
structure LessThanLatin (solution: Nat -> Symbols4) where
  row1: UniqueRegion solution { 0, 1, 2, 3}
  row2: UniqueRegion solution { 4, 5, 6, 7}
  row3: UniqueRegion solution { 8, 9,10,11}
  row4: UniqueRegion solution {12,13,14,15}
  col1: UniqueRegion solution { 0, 4, 8,12}
  col2: UniqueRegion solution { 1, 5, 9,13}
  col3: UniqueRegion solution { 2, 6,10,14}
  col4: UniqueRegion solution { 3, 7,11,15}
  -- no box constraints on this puzzle
  -- box1: UniqueRegion solution { 0, 1, 4, 5}
  -- box2: UniqueRegion solution { 2, 3, 6, 7}
  -- box3: UniqueRegion solution { 8, 9,12,13}
  -- box4: UniqueRegion solution {10,11,14,15}
  lt0_1: solution 0 < solution 1
  lt1_2: solution 1 < solution 2
  lt6_7: solution 7 < solution 6
  lt8_12: solution 12 < solution 8
  lt14_15: solution 14 < solution 15
  lt0_4: solution 0 < solution 4
  lt3_7: solution 3 < solution 7
  lt7_11: solution 7 < solution 11
  outside_grid: ∀ x, x ≥ 16 -> solution x = Symbols4.one

theorem SolveLessThanPuzzle {S : Set (Nat → Symbols4)} (H : ∀ f, f ∈ S ↔ LessThanLatin f):
  ∃! (g: Nat -> Symbols4), g ∈ S := by
  have c3: ∀ f ∈ S, f 3 = 1 := by
    -- hidden single 1, every cell in the col must be greater than 1
    intro f hf
    replace H := (H f).mp hf
    let h := (region_full_set_bijective H.col4).surjOn (Set.mem_univ 1)
    simp only [Set.mem_image, Set.mem_insert_iff, Set.mem_singleton_iff,
      exists_eq_or_imp, ↓existsAndEq, true_and] at h
    split_disjunctive_4 h
    · assumption
    · exfalso; exact not_lt_bot (h ▸ H.lt3_7)
    · exfalso; exact not_lt_bot (h ▸ H.lt7_11)
    · exfalso; exact not_lt_bot (h ▸ H.lt14_15)
  -- fill in row1, from bottom to top
  -- this process involves tracking the minimums upwards and then tracking the maximums downwards
  -- now I have a theorem to do the heavy lifting
  -- have c0min: ∀ f ∈ S, 2 ≤ f 0 := by
  --   intro f hf
  --   replace H := (H f).mp hf
  --   cases h: (f 0) <;> try decide
  --   · exfalso; exact digit_in_region h H.row1 (c3 f hf)
  -- have c1min: ∀ f ∈ S, 3 ≤ f 1 := by
  --   intro f hf
  --   replace H := (H f).mp hf
  --   exact Nat.lt_of_le_of_lt (le_trans (by decide) (c0min f hf)) H.lt0_1
  -- have c2: ∀ f ∈ S,f 2 = 4 := by
  --   intro f hf
  --   replace H := (H f).mp hf
  --   apply top_unique
  --   exact Nat.lt_of_le_of_lt (le_trans (by decide) (c1min f hf)) H.lt1_2
  -- have c1: ∀ f ∈ S, f 1 = 3 := by
  --   intro f hf
  --   replace H := (H f).mp hf
  --   refine le_antisymm (Nat.le_of_lt_succ ?_) ?_
  --   simp only [Nat.succ_eq_add_one]
  --   apply ((c2 f hf) ▸ H.lt1_2)
  --   apply c1min f hf
  -- clear c1min
  -- have c0: ∀ f ∈ S, f 0 = 2 := by
  --   intro f hf
  --   replace H := (H f).mp hf
  --   refine le_antisymm (Nat.le_of_lt_succ ?_) ?_
  --   simp only [Nat.succ_eq_add_one]
  --   apply ((c1 f hf) ▸ H.lt0_1)
  --   apply c0min f hf
  -- clear c0min
  have thermoA: ∀ f ∈ S, Thermometer f [0,1,2] := by
    intro f hf
    replace H := (H f).mp hf
    constructor
    · decide
    · simp only [List.map_cons, List.map_nil, List.isChain_cons_cons,
      List.IsChain.singleton, and_true]
      constructor
      · exact H.lt0_1
      · exact H.lt1_2
  have c0min: ∀ f ∈ S, 2 ≤ f 0 := by
    intro f hf
    replace H := (H f).mp hf
    cases h: (f 0) <;> try decide
    · exfalso; exact digit_in_region h H.row1 (c3 f hf)
  have c2max: ∀ f ∈ S, f 2 ≤ 4 := by
    intro f hf
    replace H := (H f).mp hf
    cases h: (f 2) <;> try decide
  -- now to fill the thermo
  have c0: ∀ f ∈ S, f 0 = 2 := by
    intro f hf
    apply ToNat.toNat_injective (fill_thermo (thermoA f hf)
    (c0min f hf) (c2max f hf) (by decide) 0 (by decide))
  have c1: ∀ f ∈ S, f 1 = 3 := by
    intro f hf
    apply ToNat.toNat_injective (fill_thermo (thermoA f hf)
    (c0min f hf) (c2max f hf) (by decide) 1 (by decide))
  have c2: ∀ f ∈ S, f 2 = 4 := by
    intro f hf
    apply ToNat.toNat_injective (fill_thermo (thermoA f hf)
    (c0min f hf) (c2max f hf) (by decide) 2 (by decide))
  clear thermoA c0min c2max
  -- new thermo
  have thermoA: ∀ f ∈ S, Thermometer f [7,6] := by
    intro f hf
    replace H := (H f).mp hf
    constructor
    · decide
    · simp only [List.map_cons, List.map_nil, List.isChain_cons_cons,
        List.IsChain.singleton, and_true]
      exact H.lt6_7
  have c7min: ∀ f ∈ S, 2 ≤ f 7 := by
    intro f hf
    replace H := (H f).mp hf
    cases h: (f 7) <;> try decide
    · exfalso; exact digit_in_region h H.col4 (c3 f hf)
  have c6max: ∀ f ∈ S, f 6 ≤ 3 := by
    intro f hf
    replace H := (H f).mp hf
    cases h: (f 6) <;> try decide
    · exfalso; exact digit_in_region h H.col3 (c2 f hf)
  -- now to fill the thermo
  have c6: ∀ f ∈ S, f 6 = 3 := by
    intro f hf
    apply ToNat.toNat_injective (fill_thermo (thermoA f hf)
    (c7min f hf) (c6max f hf) (by decide) 1 (by decide))
  have c7: ∀ f ∈ S, f 7 = 2 := by
    intro f hf
    apply ToNat.toNat_injective (fill_thermo (thermoA f hf)
    (c7min f hf) (c6max f hf) (by decide) 0 (by decide))
  have c4: ∀ f ∈ S, f 4 = 4 := by
    intro f hf
    replace H := (H f).mp hf
    cases h: (f 4)
    · exfalso; exact absurd H.lt0_4 (by rw [c0 f hf, h]; decide)
    · exfalso; exact absurd H.lt0_4 (by rw [c0 f hf, h]; decide)
    · exfalso; exact digit_in_region h H.row2 (c6 f hf)
    · rfl
  have c5: ∀ f ∈ S, f 5 = 1 := by
    intro f hf
    replace H := (H f).mp hf
    cases h: (f 5)
    · rfl
    · exfalso; exact digit_in_region h H.row2 (c7 f hf)
    · exfalso; exact digit_in_region h H.row2 (c6 f hf)
    · exfalso; exact digit_in_region h H.row2 (c4 f hf)
  clear thermoA c7min c6max
  have c8: ∀ f ∈ S, f 8 = 3 := by
    intro f hf
    replace H := (H f).mp hf
    cases h: (f 8)
    · exfalso; exact not_lt_bot (h ▸ H.lt8_12)
    · exfalso; exact digit_in_region h H.col1 (c0 f hf)
    · rfl
    · exfalso; exact digit_in_region h H.col1 (c4 f hf)
  have c12: ∀ f ∈ S, f 12 = 1 := by
    intro f hf
    replace H := (H f).mp hf
    cases h: (f 12)
    · rfl
    · exfalso; exact digit_in_region h H.col1 (c0 f hf)
    · exfalso; exact digit_in_region h H.col1 (c8 f hf)
    · exfalso; exact digit_in_region h H.col1 (c4 f hf)
  have c14: ∀ f ∈ S, f 14 = 2 := by
    intro f hf
    replace H := (H f).mp hf
    cases h: (f 14)
    · exfalso; exact digit_in_region h H.row4 (c12 f hf)
    · rfl
    · exfalso; exact digit_in_region h H.col3 (c6 f hf)
    · exfalso; exact digit_in_region h H.col3 (c2 f hf)
  have c10: ∀ f ∈ S, f 10 = 1 := by
    intro f hf
    replace H := (H f).mp hf
    cases h: (f 10)
    · rfl
    · exfalso; exact digit_in_region h H.col3 (c14 f hf)
    · exfalso; exact digit_in_region h H.col3 (c6 f hf)
    · exfalso; exact digit_in_region h H.col3 (c2 f hf)
  have c11: ∀ f ∈ S, f 11 = 4 := by
    intro f hf
    replace H := (H f).mp hf
    cases h: (f 11)
    · exfalso; exact digit_in_region h H.col4 (c3 f hf)
    · exfalso; exact digit_in_region h H.col4 (c7 f hf)
    · exfalso; exact digit_in_region h H.row3 (c8 f hf)
    · rfl
  have c15: ∀ f ∈ S, f 15 = 3 := by
    intro f hf
    replace H := (H f).mp hf
    cases h: (f 15)
    · exfalso; exact digit_in_region h H.col4 (c3 f hf)
    · exfalso; exact digit_in_region h H.col4 (c7 f hf)
    · rfl
    · exfalso; exact digit_in_region h H.col4 (c11 f hf)
  have c9: ∀ f ∈ S, f 9 = 2 := by
    intro f hf
    replace H := (H f).mp hf
    cases h: (f 9)
    · exfalso; exact digit_in_region h H.row3 (c10 f hf)
    · rfl
    · exfalso; exact digit_in_region h H.row3 (c8 f hf)
    · exfalso; exact digit_in_region h H.row3 (c11 f hf)
  have c13: ∀ f ∈ S, f 13 = 4 := by
    intro f hf
    replace H := (H f).mp hf
    cases h: (f 13)
    · exfalso; exact digit_in_region h H.row4 (c12 f hf)
    · exfalso; exact digit_in_region h H.row4 (c14 f hf)
    · exfalso; exact digit_in_region h H.row4 (c15 f hf)
    · rfl
  -- done solving, lets finish it out
  let digits: Array Symbols4 :=
    #[2,3,4,1,
      4,1,3,2,
      3,2,1,4,
      1,4,2,3]
  have len: digits.size = 16 := by decide
  let g : Nat → Symbols4 := fun x => digits[x]? |>.getD 1
  use g
  constructor
  · simp only
    apply (H g).mpr
    -- prove that g obeys the constraints of the puzzle
    constructor
    -- regions
    iterate 8 apply injOn_by_card; decide
    -- givens
    iterate 3 decide
    -- less thans
    iterate 5 decide
    -- and outside the grid
    intro n hn
    unfold g
    conv =>
      enter [1, 1]
      apply Array.getElem?_eq_none (by {rw [len]; assumption})
    simp
  -- prove that forall h, h = g
  intro h hh
  replace H := (H h).mp hh
  ext x
  by_cases xin: x < 16
  · interval_cases x
    · exact c0 h hh
    · exact c1 h hh
    · exact c2 h hh
    · exact c3 h hh
    · exact c4 h hh
    · exact c5 h hh
    · exact c6 h hh
    · exact c7 h hh
    · exact c8 h hh
    · exact c9 h hh
    · exact c10 h hh
    · exact c11 h hh
    · exact c12 h hh
    · exact c13 h hh
    · exact c14 h hh
    · exact c15 h hh
  rw [H.outside_grid]
  · unfold g
    simp at xin
    conv =>
      enter [2, 1]
      apply Array.getElem?_eq_none (by {rw [len]; assumption})
    simp
  push_neg at xin
  apply xin


/-
Less than theorems
the smallest symbol is never allowed to be on the greater than side of an lt
similarly for the largest symbol

-/
