import SudokuLean.Basic
import SudokuLean.Symbols4
import SudokuLean.Tactics

set_option linter.style.whitespace false

-- puzzle generated by Google Gemini, lets see if it is solvable
structure LessThanPuzzle (solution: Nat -> Symbols4) where
  row1: UniqueRegion solution { 0, 1, 2, 3}
  row2: UniqueRegion solution { 4, 5, 6, 7}
  row3: UniqueRegion solution { 8, 9,10,11}
  row4: UniqueRegion solution {12,13,14,15}
  col1: UniqueRegion solution { 0, 4, 8,12}
  col2: UniqueRegion solution { 1, 5, 9,13}
  col3: UniqueRegion solution { 2, 6,10,14}
  col4: UniqueRegion solution { 3, 7,11,15}
  box1: UniqueRegion solution { 0, 1, 4, 5}
  box2: UniqueRegion solution { 2, 3, 6, 7}
  box3: UniqueRegion solution { 8, 9,12,13}
  box4: UniqueRegion solution {10,11,14,15}
  given2: solution 2 = 4
  given11: solution 11 = 3
  given13: solution 13 = 1
  lt0_1: solution 0 < solution 1
  lt6_7: solution 7 < solution 6
  lt4_8: solution 8 < solution 4
  lt5_9: solution 5 < solution 9
  lt14_15: solution 14 < solution 15
  outside_grid: ∀ x, x ≥ 16 -> solution x = Symbols4.one

theorem SolveLessThanPuzzle {S : Set (Nat → Symbols4)} (H : ∀ f, f ∈ S ↔ LessThanPuzzle f):
  ∃! (g: Nat -> Symbols4), g ∈ S := by
  have k : IsSound S [] := by intro c d h; cases h
  have c3c7pair: ∀ f (hf:f ∈ S), Set.BijOn f {3, 7} {1, 2} := by
    intro f hf
    replace H := (H f).mp hf
    apply locked_set_from_naked_set (H.col4)
    intro c h
    rcases h with rfl | rfl
    cases h: f 3 with
    | one => decide
    | two => decide
    | three => exfalso; exact digit_in_region h H.col4 H.given11
    | four => exfalso; exact digit_in_region h H.box2 H.given2
    cases h: f 7 with
    | one => decide
    | two => decide
    | three => exfalso; exact digit_in_region h H.col4 H.given11
    | four => exfalso; exact digit_in_region h H.box2 H.given2
  replace k := add_fact k 15 4 (by
    intro f hf
    replace H := (H f).mp hf
    cases h: f 15 with
    | one => exfalso; exact locked_set_in_region h H.col4 (c3c7pair f hf)
    | two => exfalso; exact locked_set_in_region h H.col4 (c3c7pair f hf)
    | three => exfalso; exact digit_in_region h H.col4 H.given11
    | four => decide
  )
  replace k := add_fact k 6 3 (by
    intro f hf
    replace H := (H f).mp hf
    cases h: f 6 with
    | one => exfalso; exact locked_set_in_region h H.box2 (c3c7pair f hf)
    | two => exfalso; exact locked_set_in_region h H.box2 (c3c7pair f hf)
    | three => decide
    | four => exfalso; exact digit_in_region h H.box2 H.given2
  )
  have c1n4: ∀ f ∈ S, f 1 ≠ 4 := by
    intro f hf
    replace H := (H f).mp hf
    intro h; exact digit_in_region h H.row1 H.given2
  have c0c3pair: ∀ f (hf:f ∈ S), Set.BijOn f {0, 3} {1, 2} := by
    intro f hf
    replace H := (H f).mp hf
    apply locked_set_from_naked_set (H.row1)
    intro c h
    rcases h with rfl | rfl
    cases h: f 0 with
    | one => decide
    | two => decide
    | three =>
      exfalso
      let lt0_1 := H.lt0_1
      rw [h] at lt0_1
      cases h: f 1 with
      | one => rw [h] at lt0_1; contradiction
      | two => rw [h] at lt0_1; contradiction
      | three => rw [h] at lt0_1; contradiction
      | four => exact digit_in_region h H.row1 H.given2
    | four => exfalso; exact digit_in_region h H.row1 H.given2
    cases h: f 3 with
    | one => decide
    | two => decide
    | three => exfalso; exact digit_in_region h H.col4 H.given11
    | four => exfalso; exact digit_in_region h H.box2 H.given2
  replace k := add_fact k 1 3 (by
    intro f hf
    replace H := (H f).mp hf
    cases h: f 1 with
    | one => exfalso; exact locked_set_in_region h H.row1 (c0c3pair f hf)
    | two => exfalso; exact locked_set_in_region h H.row1 (c0c3pair f hf)
    | three => decide
    | four => exfalso; exact digit_in_region h H.row1 H.given2
  )
  replace k := add_fact k 14 2 (by
    intro f hf
    replace H := (H f).mp hf
    cases h: f 14 with
    | one => exfalso; exact digit_in_region h H.row4 H.given13
    | two => decide
    | three => exfalso; exact digit_in_region h H.box4 H.given11
    | four => exfalso; exact digit_in_region h H.box4 ((get_d k 15 4) f hf)
  )
  replace k := add_fact k 10 1 (by
    intro f hf
    replace H := (H f).mp hf
    cases h: f 10 with
    | one => decide
    | two => exfalso; exact digit_in_region h H.box4 ((get_d k 14 2) f hf)
    | three => exfalso; exact digit_in_region h H.box4 H.given11
    | four => exfalso; exact digit_in_region h H.box4 ((get_d k 15 4) f hf)
  )
  replace k := add_fact k 12 3 (by
    intro f hf
    replace H := (H f).mp hf
    cases h: f 12 with
    | one => exfalso; exact digit_in_region h H.row4 H.given13
    | two => exfalso; exact digit_in_region h H.row4 ((get_d k 14 2) f hf)
    | three => decide
    | four => exfalso; exact digit_in_region h H.row4 ((get_d k 15 4) f hf)
  )
  replace k := add_fact k 5 2 (by
    intro f hf
    replace H := (H f).mp hf
    cases h: f 5 with
    | one => exfalso; exact digit_in_region h H.col2 H.given13
    | two => decide
    | three => exfalso; exact digit_in_region h H.col2 ((get_d k 1 3) f hf)
    | four =>
      let lt5_9 := H.lt5_9
      rw [h] at lt5_9
      absurd lt5_9
      cases h: f 9 <;> decide
  )
  replace k := add_fact k 9 4 (by
    intro f hf
    replace H := (H f).mp hf
    cases h: f 9 with
    | one => exfalso; exact digit_in_region h H.col2 H.given13
    | two => exfalso; exact digit_in_region h H.col2 ((get_d k 5 2) f hf)
    | three => exfalso; exact digit_in_region h H.col2 ((get_d k 1 3) f hf)
    | four => decide
  )
  replace k := add_fact k 8 2 (by
    intro f hf
    replace H := (H f).mp hf
    cases h: f 8 with
    | one => exfalso; exact digit_in_region h H.row3 ((get_d k 10 1) f hf)
    | two => decide
    | three => exfalso; exact digit_in_region h H.row3 H.given11
    | four => exfalso; exact digit_in_region h H.row3 ((get_d k 9 4) f hf)
  )
  replace k := add_fact k 4 4 (by
    intro f hf
    replace H := (H f).mp hf
    cases h: f 4 with
    | one => exfalso; absurd H.lt4_8; rw [h, ((get_d k 8 2) f hf)]; decide
    | two => exfalso; absurd H.lt4_8; rw [h, ((get_d k 8 2) f hf)]; decide
    | three => exfalso; exact digit_in_region h H.row2 ((get_d k 6 3) f hf)
    | four => decide
  )
  replace k := add_fact k 0 1 (by
    intro f hf
    replace H := (H f).mp hf
    replace h := (c0c3pair f hf).mapsTo (x := 0) (by simp)
    cases h with
    | inl h => assumption
    | inr h => exfalso; exact digit_in_region h H.box1 ((get_d k 5 2) f hf)
  )
  replace k := add_fact k 3 2 (by
    intro f hf
    replace H := (H f).mp hf
    simpa using locked_set_reducton (c0c3pair f hf) ((get_d k 0 1) f hf)
  )
  replace k := add_fact k 7 1 (by
    intro f hf
    replace H := (H f).mp hf
    simpa using locked_set_reducton (c3c7pair f hf) ((get_d k 3 2) f hf)
  )
  clear c3c7pair c1n4 c0c3pair
  -- done solving, lets finish it out
  let digits: Array Symbols4 :=
    #[1,3,4,2,
      4,2,3,1,
      2,4,1,3,
      3,1,2,4]
  have len: digits.size = 16 := by decide
  let g : Nat → Symbols4 := fun x => digits[x]? |>.getD 1
  use g
  constructor
  · simp only
    apply (H g).mpr
    -- prove that g obeys the constraints of the puzzle
    constructor
    -- regions
    iterate 12 apply injOn_by_card; decide
    -- givens
    iterate 3 decide
    -- less thans
    iterate 5 decide
    -- and outside the grid
    intro n hn
    unfold g
    conv =>
      enter [1, 1]
      apply Array.getElem?_eq_none (by {rw [len]; assumption})
    simp
  -- prove that forall h, h = g
  intro h hh
  replace H := (H h).mp hh
  ext x
  by_cases xin: x < 16
  · interval_cases x
    · exact (get_d k 0 1) h hh
    · exact (get_d k 1 3) h hh
    · exact H.given2
    · exact (get_d k 3 2) h hh
    · exact (get_d k 4 4) h hh
    · exact (get_d k 5 2) h hh
    · exact (get_d k 6 3) h hh
    · exact (get_d k 7 1) h hh
    · exact (get_d k 8 2) h hh
    · exact (get_d k 9 4) h hh
    · exact (get_d k 10 1) h hh
    · exact H.given11
    · exact (get_d k 12 3) h hh
    · exact H.given13
    · exact (get_d k 14 2) h hh
    · exact (get_d k 15 4) h hh
  rw [H.outside_grid]
  · unfold g
    simp at xin
    conv =>
      enter [2, 1]
      apply Array.getElem?_eq_none (by {rw [len]; assumption})
    simp
  push_neg at xin
  apply xin


/-
Less than theorems
the smallest symbol is never allowed to be on the greater than side of an lt
similarly for the largest symbol

-/
